export const TALENT_BRIDGE_PROTOCOL_V1 = "HCM_AURA_TALENT_BRIDGE_V1";

export const TALENT_BRIDGE_CONSUMER_ID_V1 =
  "aura-hcm-talent-bridge-v1";

export const TALENT_BRIDGE_AUDIENCE_V1 =
  "aura-intelligence://HCM_AURA_TALENT_BRIDGE_V1";

export const TALENT_AUTH_SECRET_NAME_V1 =
  "HCM_AURA_TALENT_BRIDGE_V1_CREDENTIAL_SET";

export const TALENT_TENANT_REGISTRY_COLLECTION_V1 =
  "hcmAuraTalentTenantMappingsV1";

export const TALENT_MAX_RAW_BODY_BYTES_V1 = 262_144;

export const TALENT_EVALUATION_MODE_V1 = "EVALUATION";
export const TALENT_ADVISORY_ONLY_V1 = true;
export const TALENT_HUMAN_DECISION_REQUIRED_V1 = true;
export const TALENT_EMPLOYMENT_ACTION_ALLOWED_V1 = false;
export const TALENT_SCORE_BLENDING_ALLOWED_V1 = false;
export const TALENT_JOB_PROFILE_REF_V1 = "JOB_PROFILE_1";
export const TALENT_SUBJECT_REF_V1 = "INTERNAL_1";
export const TALENT_SUBJECT_TYPE_V1 = "INTERNAL";
export const TALENT_PERFORMANCE_EVIDENCE_REF_V1 = "PERFORMANCE_1";
export const TALENT_HARD_STOP_EVIDENCE_REF_V1 = "HARD_STOP_1";

export const TALENT_RISK_LEVELS_V1 = ["LOW", "MEDIUM", "HIGH"] as const;

export const TALENT_MATRIX_CELLS_V1 = [
  "LOW_PERFORMANCE_LOW_POTENTIAL",
  "LOW_PERFORMANCE_MEDIUM_POTENTIAL",
  "LOW_PERFORMANCE_HIGH_POTENTIAL",
  "MEDIUM_PERFORMANCE_LOW_POTENTIAL",
  "MEDIUM_PERFORMANCE_MEDIUM_POTENTIAL",
  "MEDIUM_PERFORMANCE_HIGH_POTENTIAL",
  "HIGH_PERFORMANCE_LOW_POTENTIAL",
  "HIGH_PERFORMANCE_MEDIUM_POTENTIAL",
  "HIGH_PERFORMANCE_HIGH_POTENTIAL",
] as const;

export const TALENT_HARD_STOP_RISK_FLAGS_V1 = [
  "INSUFFICIENT_PERFORMANCE_HISTORY",
  "MISSING_PERFORMANCE_HISTORY",
  "LOW_PERFORMANCE_UNDER_THRESHOLD",
  "LOW_POTENTIAL_UNDER_THRESHOLD",
  "LOW_READINESS_UNDER_THRESHOLD",
  "MANDATORY_CERTIFICATION_MISSING",
  "MANDATORY_CERTIFICATION_EXPIRED",
  "MANDATORY_CERTIFICATION_REJECTED",
  "MANDATORY_CERTIFICATION_PENDING",
  "CRITICAL_SKILL_MISSING",
  "CRITICAL_SKILL_PENDING",
  "DISCIPLINARY_INCIDENTS_EXCEEDED",
  "SEVERE_DISCIPLINARY_INCIDENT_RECENT",
  "DISCIPLINARY_HISTORY_WARNING",
  "INCOMPLETE_TALENT_DATA",
  "MISSING_MANAGER",
  "LOW_CONFIDENCE",
] as const;

export const TALENT_EVIDENCE_QUALITY_VALUES_V1 = [
  "EVIDENCE_COMPLETE",
  "EVIDENCE_INCOMPLETE",
  "VALIDATION_PENDING",
  "CONFIDENCE_INSUFFICIENT",
] as const;

export const TALENT_PROJECTS_BY_ENVIRONMENT_V1 = {
  preview: "aura-intel-preview",
  staging: "aura-intel-staging",
  production: null,
} as const;

export type TalentBridgeEnvironmentV1 = "preview" | "staging";
